### ISSUE TITLE
Unable to find component: []

### ISSUE THREAD

**Issue by faizananwerali** [solutionforest/filament-tab-plugin#2]
<img width="1311" alt="Screenshot 2023-07-13 at 3 58 06 AM" src="https://github.com/solutionforest/filament-tab-plugin/assets/12691366/c404511c-5cf3-4dae-b846-2e0a11268dea">

I tired to make it but I failed many times, don't know why is this error showing

**Comment by lam0819** [comment]
not sure your case, if you have github we can check it out.

but we will achieve this project since filament3 support tabs now.
https://beta.filamentphp.com/docs/3.x/infolists/layout/tabs
